### ISSUE TITLE
RE: CC0 License

### ISSUE THREAD

**Issue by cyphar** [MEM-AEAD/mem-aead#1]
I'd recommend using something like the [unlicense](http://unlicense.org/), if you'd like to commit your software to the public domain (or as close as possible). However, IMO a much better license choice would be something like Apache 2.0 (which in some ways is more beneficial to user freedom than public domain as it also provides users patent grants that protect their freedoms).

Creative Commons licenses are not a good idea for software, for two main reasons:
1. They are not designed for software, so certain language isn't properly suited to the field of software (which is not a creative work in the same way that a piece of music or a poem is a creative work). Terms such as "reproduce, adapt, distribute, perform, display, communicate, and translate" are not the best choice of wording for a software license.
2. The CC licenses do not protect users from software patents. So while your work may, in principle, be free software (or public domain) -- users may not be able to use the software in freedom.

**Comment by sneves** [comment]
CC0 has wording for software, and the FSF [explicitly recommends CC0 over Unlicense](https://www.gnu.org/licenses/license-list.en.html#Unlicense) for public domain dedications.

The OSI [doesn't like any public domain license](http://opensource.org/faq#cc-zero), so there's nothing to be done about that. Patents seem to be the problem there, but I think Apache 2.0 is not a better choice, purely by being incompatible with GPLv2. It seems to me more harm is done by excluding a significant amount of free software to prevent potential software patent issues (that in a small project like this are vanishingly unlikely to come up).

Of course, this is experimental research software, so I would discourage _any_ project from adopting this code unless it is also for research purposes. This may change over time, and so may also the licensing.

**Comment by cyphar** [comment]
> CC0 has wording for software,

It wasn't designed to be a software license, all other CC licenses are incompatible with most free software licenses, and [CC **themselves** stated that you should not use CC licenses for software](http://webcache.googleusercontent.com/search?q=cache:GFcsVQ4fTLMJ:https://creativecommons.org/weblog/2011/04/15/27081+&cd=1&hl=en&ct=clnk&gl=au) and were surprised when the FSF added CC0 to their list of approved licenses. After all, in the FAQ:

> The only categories of works for which CC does not recommend its licenses are computer software and hardware.

> and the FSF explicitly recommends CC0 over Unlicense for public domain dedications.

Their reasoning is that CC0 is more "battle tested", but they glaze over the fact that the CC0 *explicitly states* that the owner retains patent rights.

> but I think Apache 2.0 is not a better choice, purely by being incompatible with GPLv2.

I just want to point out that this isn't correct. Both Apache and the FSF agree that software under the Apache 2.0 license is compatible with the GPL (since it allows for sublicensing). Sure, GPL software can't be made into Apache 2.0 software, but that's not the point. I'm not sure where you got this idea from.

> It seems to me more harm is done by excluding a significant amount of free software to prevent potential software patent issues (that in a small project like this are vanishingly unlikely to come up).

> This may change over time, and so may also the licensing.

I'm not sure that's entirely valid (a public domain contribution means that you've relinquished all rights you had under copyright law). After all, from the CC0:

> [...] fully intending that such Waiver shall not be subject to revocation, rescission, cancellation, termination, or any other legal or equitable action to disrupt the quiet enjoyment of the Work by the public as contemplated by Affirmer's express Statement of Purpose.

Meh, it's your choice what license you go with. It just bothers me when people use licenses for artistic works for software.

**Comment by cyphar** [comment]
I don't agree that using CC0 for software is a good idea (it wasn't made to be a software license, as evidenced by an [old blog post which has since been removed](http://webcache.googleusercontent.com/search?q=cache:GFcsVQ4fTLMJ:https://creativecommons.org/weblog/2011/04/15/27081+&cd=1&hl=en&ct=clnk&gl=au)). But your license choice is up to you.
